services:  
  minio:
    env_file: .env
    image: minio/minio:latest
    ports:
      - "9000:${MINIO_PORT}"      # API port
      - "9001:9001"      # Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  postgresql:
    env_file: .env
    image: postgres:latest
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"

  redis:
    image: redis/redis-stack-server
    env_file: .env
    container_name: "redis"
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USER} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"

  fastapi: 
    build: .
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_DRIVER_NAME: "postgresql+asyncpg"
      DATABASE_HOST: postgresql
      REDIS_URL: "redis://${REDIS_USER}:${REDIS_PASSWORD}@redis:6379/0"
      MINIO_URL: "minio:${MINIO_PORT}"
    depends_on:
      - postgresql
      - minio
      - redis

volumes:
  minio_data:
    driver: local 